<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleSeeder extends Seeder
{
    public function run(): void
    {
        // Create roles
        $superAdmin = Role::firstOrCreate(['name' => 'super_admin']);
        $admin = Role::firstOrCreate(['name' => 'admin']);

        // Create all permissions for User resource
        $permissions = [
            // User permissions (singular - based on model name)
            'ViewAny:User',
            'View:User',
            'Create:User',
            'Update:User',
            'Delete:User',
            'DeleteAny:User',
            'ForceDelete:User',
            'ForceDeleteAny:User',
            'Restore:User',
            'RestoreAny:User',
            'Replicate:User',
            'Reorder:User',
            // Role permissions
            'ViewAny:Role',
            'View:Role',
            'Create:Role',
            'Update:Role',
            'Delete:Role',
            'DeleteAny:Role',
            'ForceDelete:Role',
            'ForceDeleteAny:Role',
            'Restore:Role',
            'RestoreAny:Role',
            'Replicate:Role',
            'Reorder:Role',
            // Activity Log permissions
            'ViewAny:Activity',
            'View:Activity',
            // Sekolah permissions
            'ViewAny:Sekolah',
            'View:Sekolah',
            'Create:Sekolah',
            'Update:Sekolah',
            'Delete:Sekolah',
            'DeleteAny:Sekolah',
            'ForceDelete:Sekolah',
            'ForceDeleteAny:Sekolah',
            'Restore:Sekolah',
            'RestoreAny:Sekolah',
            'Replicate:Sekolah',
            'Reorder:Sekolah',
            // Informasi permissions
            'ViewAny:Informasi',
            'View:Informasi',
            'Create:Informasi',
            'Update:Informasi',
            'Delete:Informasi',
            'DeleteAny:Informasi',
            'ForceDelete:Informasi',
            'ForceDeleteAny:Informasi',
            'Restore:Informasi',
            'RestoreAny:Informasi',
            'Replicate:Informasi',
            'Reorder:Informasi',
            // JabatanPegawai permissions
            'ViewAny:JabatanPegawai',
            'View:JabatanPegawai',
            'Create:JabatanPegawai',
            'Update:JabatanPegawai',
            'Delete:JabatanPegawai',
            'DeleteAny:JabatanPegawai',
            'ForceDelete:JabatanPegawai',
            'ForceDeleteAny:JabatanPegawai',
            'Restore:JabatanPegawai',
            'RestoreAny:JabatanPegawai',
            'Replicate:JabatanPegawai',
            'Reorder:JabatanPegawai',
            // Pegawai permissions
            'ViewAny:Pegawai',
            'View:Pegawai',
            'Create:Pegawai',
            'Update:Pegawai',
            'Delete:Pegawai',
            'DeleteAny:Pegawai',
            'ForceDelete:Pegawai',
            'ForceDeleteAny:Pegawai',
            'Restore:Pegawai',
            'RestoreAny:Pegawai',
            'Replicate:Pegawai',
            'Reorder:Pegawai',
            // TahunAjaran permissions
            'ViewAny:TahunAjaran',
            'View:TahunAjaran',
            'Create:TahunAjaran',
            'Update:TahunAjaran',
            'Delete:TahunAjaran',
            'DeleteAny:TahunAjaran',
            'ForceDelete:TahunAjaran',
            'ForceDeleteAny:TahunAjaran',
            'Restore:TahunAjaran',
            'RestoreAny:TahunAjaran',
            'Replicate:TahunAjaran',
            'Reorder:TahunAjaran',
            // Semester permissions
            'ViewAny:Semester',
            'View:Semester',
            'Create:Semester',
            'Update:Semester',
            'Delete:Semester',
            'DeleteAny:Semester',
            'ForceDelete:Semester',
            'ForceDeleteAny:Semester',
            'Restore:Semester',
            'RestoreAny:Semester',
            'Replicate:Semester',
            'Reorder:Semester',
            // MataPelajaran permissions
            'ViewAny:MataPelajaran',
            'View:MataPelajaran',
            'Create:MataPelajaran',
            'Update:MataPelajaran',
            'Delete:MataPelajaran',
            'DeleteAny:MataPelajaran',
            'ForceDelete:MataPelajaran',
            'ForceDeleteAny:MataPelajaran',
            'Restore:MataPelajaran',
            'RestoreAny:MataPelajaran',
            'Replicate:MataPelajaran',
            'Reorder:MataPelajaran',
            // JamPelajaran permissions
            'ViewAny:JamPelajaran',
            'View:JamPelajaran',
            'Create:JamPelajaran',
            'Update:JamPelajaran',
            'Delete:JamPelajaran',
            'DeleteAny:JamPelajaran',
            'ForceDelete:JamPelajaran',
            'ForceDeleteAny:JamPelajaran',
            'Restore:JamPelajaran',
            'RestoreAny:JamPelajaran',
            'Replicate:JamPelajaran',
            'Reorder:JamPelajaran',
            // Kelas permissions
            'ViewAny:Kelas',
            'View:Kelas',
            'Create:Kelas',
            'Update:Kelas',
            'Delete:Kelas',
            'DeleteAny:Kelas',
            'ForceDelete:Kelas',
            'ForceDeleteAny:Kelas',
            'Restore:Kelas',
            'RestoreAny:Kelas',
            'Replicate:Kelas',
            'Reorder:Kelas',
            // Siswa permissions
            'ViewAny:Siswa',
            'View:Siswa',
            'Create:Siswa',
            'Update:Siswa',
            'Delete:Siswa',
            'DeleteAny:Siswa',
            'ForceDelete:Siswa',
            'ForceDeleteAny:Siswa',
            'Restore:Siswa',
            'RestoreAny:Siswa',
            'Replicate:Siswa',
            'Reorder:Siswa',
            // JadwalPelajaran permissions
            'ViewAny:JadwalPelajaran',
            'View:JadwalPelajaran',
            'Create:JadwalPelajaran',
            'Update:JadwalPelajaran',
            'Delete:JadwalPelajaran',
            'DeleteAny:JadwalPelajaran',
            'ForceDelete:JadwalPelajaran',
            'ForceDeleteAny:JadwalPelajaran',
            'Restore:JadwalPelajaran',
            'RestoreAny:JadwalPelajaran',
            'Replicate:JadwalPelajaran',
            'Reorder:JadwalPelajaran',
            // Tahfidz permissions
            'ViewAny:Tahfidz',
            'View:Tahfidz',
            'Create:Tahfidz',
            'Update:Tahfidz',
            'Delete:Tahfidz',
            'DeleteAny:Tahfidz',
            'ForceDelete:Tahfidz',
            'ForceDeleteAny:Tahfidz',
            'Restore:Tahfidz',
            'RestoreAny:Tahfidz',
            'Replicate:Tahfidz',
            'Reorder:Tahfidz',
            // IzinKeluar permissions
            'ViewAny:IzinKeluar',
            'View:IzinKeluar',
            'Create:IzinKeluar',
            'Update:IzinKeluar',
            'Delete:IzinKeluar',
            'DeleteAny:IzinKeluar',
            'ForceDelete:IzinKeluar',
            'ForceDeleteAny:IzinKeluar',
            'Restore:IzinKeluar',
            'RestoreAny:IzinKeluar',
            'Replicate:IzinKeluar',
            'Reorder:IzinKeluar',
            // IzinPulang permissions
            'ViewAny:IzinPulang',
            'View:IzinPulang',
            'Create:IzinPulang',
            'Update:IzinPulang',
            'Delete:IzinPulang',
            'DeleteAny:IzinPulang',
            'ForceDelete:IzinPulang',
            'ForceDeleteAny:IzinPulang',
            'Restore:IzinPulang',
            'RestoreAny:IzinPulang',
            'Replicate:IzinPulang',
            'Reorder:IzinPulang',
            // Prestasi permissions
            'ViewAny:Prestasi',
            'View:Prestasi',
            'Create:Prestasi',
            'Update:Prestasi',
            'Delete:Prestasi',
            'DeleteAny:Prestasi',
            'ForceDelete:Prestasi',
            'ForceDeleteAny:Prestasi',
            'Restore:Prestasi',
            'RestoreAny:Prestasi',
            'Replicate:Prestasi',
            'Reorder:Prestasi',
            // Pelanggaran permissions
            'ViewAny:Pelanggaran',
            'View:Pelanggaran',
            'Create:Pelanggaran',
            'Update:Pelanggaran',
            'Delete:Pelanggaran',
            'DeleteAny:Pelanggaran',
            'ForceDelete:Pelanggaran',
            'ForceDeleteAny:Pelanggaran',
            'Restore:Pelanggaran',
            'RestoreAny:Pelanggaran',
            'Replicate:Pelanggaran',
            'Reorder:Pelanggaran',
            // Konseling permissions
            'ViewAny:Konseling',
            'View:Konseling',
            'Create:Konseling',
            'Update:Konseling',
            'Delete:Konseling',
            'DeleteAny:Konseling',
            'ForceDelete:Konseling',
            'ForceDeleteAny:Konseling',
            'Restore:Konseling',
            'RestoreAny:Konseling',
            'Replicate:Konseling',
            'Reorder:Konseling',
            // KenaikanKelas permissions
            'ViewAny:KenaikanKelas',
            'View:KenaikanKelas',
            'Create:KenaikanKelas',
            'Update:KenaikanKelas',
            'Delete:KenaikanKelas',
            'DeleteAny:KenaikanKelas',
            'ForceDelete:KenaikanKelas',
            'ForceDeleteAny:KenaikanKelas',
            'Restore:KenaikanKelas',
            'RestoreAny:KenaikanKelas',
            'Replicate:KenaikanKelas',
            'Reorder:KenaikanKelas',
            // Kelulusan permissions
            'ViewAny:Kelulusan',
            'View:Kelulusan',
            'Create:Kelulusan',
            'Update:Kelulusan',
            'Delete:Kelulusan',
            'DeleteAny:Kelulusan',
            'ForceDelete:Kelulusan',
            'ForceDeleteAny:Kelulusan',
            'Restore:Kelulusan',
            'RestoreAny:Kelulusan',
            'Replicate:Kelulusan',
            'Reorder:Kelulusan',
            // KategoriPembayaran permissions
            'ViewAny:KategoriPembayaran',
            'View:KategoriPembayaran',
            'Create:KategoriPembayaran',
            'Update:KategoriPembayaran',
            'Delete:KategoriPembayaran',
            'DeleteAny:KategoriPembayaran',
            'ForceDelete:KategoriPembayaran',
            'ForceDeleteAny:KategoriPembayaran',
            'Restore:KategoriPembayaran',
            'RestoreAny:KategoriPembayaran',
            'Replicate:KategoriPembayaran',
            'Reorder:KategoriPembayaran',
            // JenisPembayaran permissions
            'ViewAny:JenisPembayaran',
            'View:JenisPembayaran',
            'Create:JenisPembayaran',
            'Update:JenisPembayaran',
            'Delete:JenisPembayaran',
            'DeleteAny:JenisPembayaran',
            'ForceDelete:JenisPembayaran',
            'ForceDeleteAny:JenisPembayaran',
            'Restore:JenisPembayaran',
            'RestoreAny:JenisPembayaran',
            'Replicate:JenisPembayaran',
            'Reorder:JenisPembayaran',
            // TagihanSiswa permissions
            'ViewAny:TagihanSiswa',
            'View:TagihanSiswa',
            'Create:TagihanSiswa',
            'Update:TagihanSiswa',
            'Delete:TagihanSiswa',
            'DeleteAny:TagihanSiswa',
            'ForceDelete:TagihanSiswa',
            'ForceDeleteAny:TagihanSiswa',
            'Restore:TagihanSiswa',
            'RestoreAny:TagihanSiswa',
            'Replicate:TagihanSiswa',
            'Reorder:TagihanSiswa',
            // Pembayaran permissions
            'ViewAny:Pembayaran',
            'View:Pembayaran',
            'Create:Pembayaran',
            'Update:Pembayaran',
            'Delete:Pembayaran',
            'DeleteAny:Pembayaran',
            'ForceDelete:Pembayaran',
            'ForceDeleteAny:Pembayaran',
            'Restore:Pembayaran',
            'RestoreAny:Pembayaran',
            'Replicate:Pembayaran',
            'Reorder:Pembayaran',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission]);
        }

        // Give all permissions to super_admin
        $superAdmin->syncPermissions(Permission::all());

        // Give limited permissions to admin
        $admin->syncPermissions([
            'ViewAny:User',
            'View:User',
            'Create:User',
            'Update:User',
            'ViewAny:Role',
            'View:Role',
            'ViewAny:Activity',
            'View:Activity',
            'ViewAny:Sekolah',
            'View:Sekolah',
            'ViewAny:Informasi',
            'View:Informasi',
            'Create:Informasi',
            'Update:Informasi',
            'ViewAny:JabatanPegawai',
            'View:JabatanPegawai',
            'ViewAny:Pegawai',
            'View:Pegawai',
            'Create:Pegawai',
            'Update:Pegawai',
            'ViewAny:TahunAjaran',
            'View:TahunAjaran',
            'ViewAny:Semester',
            'View:Semester',
            'ViewAny:MataPelajaran',
            'View:MataPelajaran',
            'ViewAny:JamPelajaran',
            'View:JamPelajaran',
            'ViewAny:Kelas',
            'View:Kelas',
            'Create:Kelas',
            'Update:Kelas',
            'ViewAny:Siswa',
            'View:Siswa',
            'Create:Siswa',
            'Update:Siswa',
            'ViewAny:JadwalPelajaran',
            'View:JadwalPelajaran',
            'Create:JadwalPelajaran',
            'Update:JadwalPelajaran',
            'ViewAny:Tahfidz',
            'View:Tahfidz',
            'Create:Tahfidz',
            'Update:Tahfidz',
            'ViewAny:IzinKeluar',
            'View:IzinKeluar',
            'Create:IzinKeluar',
            'Update:IzinKeluar',
            'ViewAny:IzinPulang',
            'View:IzinPulang',
            'Create:IzinPulang',
            'Update:IzinPulang',
            'ViewAny:Prestasi',
            'View:Prestasi',
            'Create:Prestasi',
            'Update:Prestasi',
            'ViewAny:Pelanggaran',
            'View:Pelanggaran',
            'Create:Pelanggaran',
            'Update:Pelanggaran',
            'ViewAny:Konseling',
            'View:Konseling',
            'Create:Konseling',
            'Update:Konseling',
            'ViewAny:KenaikanKelas',
            'View:KenaikanKelas',
            'Create:KenaikanKelas',
            'Update:KenaikanKelas',
            'ViewAny:Kelulusan',
            'View:Kelulusan',
            'Create:Kelulusan',
            'Update:Kelulusan',
            'ViewAny:KategoriPembayaran',
            'View:KategoriPembayaran',
            'Create:KategoriPembayaran',
            'Update:KategoriPembayaran',
            'ViewAny:JenisPembayaran',
            'View:JenisPembayaran',
            'Create:JenisPembayaran',
            'Update:JenisPembayaran',
            'ViewAny:TagihanSiswa',
            'View:TagihanSiswa',
            'Create:TagihanSiswa',
            'Update:TagihanSiswa',
            'ViewAny:Pembayaran',
            'View:Pembayaran',
            'Create:Pembayaran',
            'Update:Pembayaran',
        ]);
    }
}
